package:
  name: exact_diag_py
  version: "0.0.1b"

source:
#  git_rev: "0.0.1-beta"
  git_url: https://github.com/weinbe58/exact_diag_py.git

requirements:
  build:
    - python
    - numpy >=1.8

  run:
    - python
    - numpy >=1.8
    - scipy >=0.14

test:
  imports:
    - numpy 
    - scipy 

about:
  home: https://github.com/weinbe58/exact_diag_py
  license: MET
