package:
  name: exact_diag_py
  version: "0.1.0"

source:
  git_url: https://github.com/weinbe58/exact_diag_py
  git_tag: 0.1.0

requirements:
  build:
    - python
    - numpy >=1.10

  run:
    - python
    - numpy >=1.10
    - scipy >=0.14

test:
  imports:
    - numpy 
    - scipy 

about:
  home: https://github.com/weinbe58/exact_diag_py
  license: MET
