package:
  name: qspin
  version: "0.1.0b"

source:
  path: ./

requirements:
  build:
    - python
    - numpy >=1.10

  run:
    - python
    - numpy
    - scipy
    - joblib
	- matplotlib

test:
  imports:
    - numpy 
    - scipy 

about:
  home: https://github.com/weinbe58/qspin.git
  license: MET
