package:
  name: quspin
  version: "0.2.7b"

source:
  path: ./

build:
  run_exports:
    - libstdc++ {{ pin_compatible('g++', 'x') }}  # [unix]
    - libsgcc {{ pin_compatible('gcc', 'x') }}  # [unix]

requirements:
  build:
    - python {{ python }}
    - numpy >=1.10.0
 
  run:
    - python {{ python }}
    - numpy >=1.10.0
    - scipy >=0.19.0
    - six
    - joblib
    - matplotlib
    - dill

test:
  imports:
    - numpy 
    - scipy

about:
  home: https://github.com/weinbe58/QuSpin.git
  license: MET
