package:
  name: quspin
  version: "0.2.3b"

source:
  path: ./

requirements:
  build:
    - python
    - numpy >=1.10

  run:
    - python
    - numpy >=1.10
    - scipy >=0.18.0
    - six
    - joblib
    - matplotlib

test:
  imports:
    - numpy 
    - scipy

about:
  home: https://github.com/weinbe58/qspin.git
  license: MET
