package:
  name: QuSpin
  version: "0.1.0"

source:
  path: ./

requirements:
  build:
    - python
    - numpy >=1.10

  run:
    - python
    - numpy >=1.10
    - scipy >=0.14.0
    - joblib
    - matplotlib

test:
  imports:
    - numpy 
    - scipy

about:
  home: https://github.com/weinbe58/qspin.git
  license: MET
