package:
  name: exact_diag_py
  version: "0.0.1a"

source:
  git_rev: "0.0.1-alpha"
  git_url: https://github.com/weinbe58/exact_diag_py.git

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - numpy
    - scipy

about:
  home: https://github.com/weinbe58/exact_diag_py
  license: MIT
