package:
  name: quspin
  version: "0.2.8"

source:
  path: ./

 

requirements:
  build:
    - {{compiler('cxx')}} # [unix]
    - python {{ python }}
    - numpy >=1.10.0
 
    
  run:
    - libgcc # [linux]
    - libstdcxx # [linux]
    - clang # [os-x]
    - clangxx # [os-x]
    - python {{ python }}
    - numpy >=1.10.0
    - scipy >=0.19.0
    - six
    - joblib
    - matplotlib
    - dill
    
test:
  imports:
    - numpy 
    - scipy

about:
  home: https://github.com/weinbe58/QuSpin.git
  license: BSD-3
