package:
  name: qspin
  version: "0.1.0b"

source:
  path: ./

requirements:
  build:
    - python
    - numpy >= 0.1.10

  run:
    - python
    - numpy >= 0.1.10
    - scipy >= 0.14.0
    - joblib
    - matplotlib

test:
  imports:
    - numpy >= 0.1.10
    - scipy >= 0.14.0

about:
  home: https://github.com/weinbe58/qspin.git
  license: MET
