package:
  name: quspin
  version: "0.2.7"

source:
  path: ./

 

requirements:
  build:
    - {{compiler('cxx')}}
    - python {{ python }}
    - numpy >=1.10.0
 
    
  run:
    - {{compiler('cxx')}}
    - python {{ python }}
    - numpy >=1.10.0
    - scipy >=0.19.0
    - six
    - joblib
    - matplotlib
    - dill
    
test:
  imports:
    - numpy 
    - scipy

about:
  home: https://github.com/weinbe58/QuSpin.git
  license: BSD-3
