package:
  name: quspin
  version: "0.3.1b"

source:
  path: ./

 

requirements:
  host:
    - python {{ python }}
    - numpy >=1.10.0

  build:
    - {{compiler('cxx')}} # [unix]
 
    
  run:
    - libgcc # [linux]
    - libgcc-ng # [linux]
    - libstdcxx-ng # [linux]
    - clang # [osx]
    - clangxx # [osx]
    - libcxx # [osx]
    - llvm-openmp #[osx]
    - python {{ python }}
    - numpy >=1.10.0
    - scipy >=0.19.0
    - six
    - joblib
    - matplotlib
    - dill
    - gmpy2 
    - numba
    
test:
  imports:
    - numpy 
    - scipy

about:
  home: https://github.com/weinbe58/QuSpin.git
  license: BSD-3
