package:
  name: quspin
  version: "0.3.1b"

source:
  path: ./

 

requirements:
  host:
    - python {{ python }}
    - numpy >=1.10.0

  build:
    - {{compiler('cxx')}} # [unix and win]
    - llvm-openmp # [osx] 
    - llvm # [osx]

  run:
    - llvm-openmp # [osx]
    - llvm # [osx]
    - python {{ python }}
    - numpy >=1.10.0
    - scipy >=0.19.0
    - six
    - joblib
    - matplotlib
    - dill
    - gmpy2 
    - numba
    
test:
  imports:
    - quspin 

about:
  home: https://github.com/weinbe58/QuSpin.git
  license: BSD-3
